### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by renatorib** [avuenja/otaac#11]
O cake tem um [sistema de themes](http://book.cakephp.org/2.0/en/views/themes.html) que é bem fácil de implementar. De uma maneira prática, vocês criariam os arquivos e selecionaria no controller `$this->theme = 'MyTheme';` semelhante quando faz pra trocar de layout. 

A estrutura dos arquivos ficariam assim:
`/app/View/Themed/{Theme}/{Controller}/{action}.ctp`
Por exemplo:
`/app/View/Themed/MyTheme/Characters/create.ctp`

Daí minha dica seria gravar o theme default no arquivo de configuração e puxar dentro do AppController.

Com isso daria pra criar temas modulares, até usando plugins.

Bom, fica aqui minha dica, xD
Abraçøs

**Comment by renatorib** [comment]
limdjo

**Comment by meccin** [comment]
<3
