### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by brunominervino** [avuenja/otaac#13]
@celopeccin vamos criar uma lista aqui do que precisa ser feito até porque quem quiser compartilhar algo, saber do que estamos precisando.

Eu queria chegar a ponto de lançarmos uma versão beta em breve, o que acha?

**Comment by meccin** [comment]
Olá @brunominervino, a lista já existia, porém devo dar mais destaque a ela acho. [To-Do](https://github.com/celopeccin/otaac/wiki/To-Do)

Eu quero lançar um release também, mas tempo sumiu quase, mas estarei trabalhando em cima de algumas partes básicas como os sistemas que envolvem a conta. Me chama no telefone para conversarmos.
