### ISSUE TITLE
Validação do Sexo

### ISSUE THREAD

**Issue by gpedro** [avuenja/otaac#5]
Se eu der um hardcoded no campo de sexo, ele insere qualquer valor no banco. É similar ao que eu resolvi nas vocações pelo commit 2c26a99d4dcdb65b451bf6c0d6ffc3d646818663.

**Comment by meccin** [comment]
Resolvido 0a1a8ec11d9d403a73c6edfa47162b0a54f4f2f7
Obrigado por reportar.
